# Site settings
title: Rebel Tools
email: your-email@domain.com
url: http://cubiclerebels.com
description: "We are a bunch of free multi-disciplinary individuals comprising of software and hardware engineers, designers and mobile specialists. Each of us with years of experience working in this line, you can be assured you will always be covered by the best."

# Header settings
header_title: Rebel Tools

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FAFAFA #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  dark: 3E3E3E


# Footer settings
footer:
  copyright: Cubicle Rebels
  location: Location
  social: Around the Web
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/ios
  - title: github
    url: http://github.com/matthewcheok

# Postal address (add as many lines as necessary)
address:
  - line: 13 Lorong 24A Geylang Road
  - line: Singapore 388667

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
sass:
    sass_dir: _sass